int _putchar(char c);
int _isupper(int x);
int _isdigit(int x);
void print_triangle(int size);
int main(void);
void print_number(int n);
int mul(int x, int y);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
int main(void);
